version: '3'
services:
  n1:
    image: cassandra:latest
    networks:
      - cluster
  n2:
    image: cassandra:latest
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
    depends_on:
      - n1
  n3:
    image: cassandra:latest
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
    depends_on:
      - n1
networks:
  cluster:
